#Menggunaakn docker compose versio sekian
version: "3.7"

#Mendeklarasikan services
services:
  #Membuat service dengan nama item-app
  item-app:
    #mengambil base image
    image: ghcr.io/tioramadhn/item-app:v1
    #mengekpost port 8080 dan membuat port forwarding ke port 80 host
    ports:
      - "80:8080"
    #Service akan dijalankan setalah item-db
    depends_on:
      - item-db
    #Membuat agar restart jika terjadi kegagalan
    restart: always

  #Membuat service dengan nama item-db
  item-db:
    #mengambil base image mongo:3 dari docker hub
    image: mongo:3
    #menggunakan volume app-db dengan target /data/db
    volumes:
      - app-db:/data/db
    #container akan restart jika terjadi kegagalan
    restart: always

volumes:
  #membuat volume app-db
  app-db:
